### PR TITLE
Fix wall glitch with some loose math. Move tests to correct place.

### LINKED ISSUE #232: One way platforms are no longer working.
#229 Broke 1-way platforms. The commented out section dictating if we can ignore collisions or not was removed without knowing why it was there. I just remembered that one-way platforms are the reason this existed. Replace this (re-implement it since it was causing other issues) and expand test coverage over it.

### PR DESCRIPTION
**Pull request by MondayHopscotch**
fixes #232

### CODE REVIEW

File: jump-core/src/main/java/com/bitdecay/jump/collision/CollisionUtilities.java [hunk 1]
```diff
@@ -54,26 +56,26 @@ private static boolean canSkipAxis(BitPoint axis, Manifold manifold) {
...
         for (Manifold manifold : bundle.getCandidates()) {
             dotProd = relativeMovement.dot(manifold.axis);
             if (dotProd != 0 && !MathUtils.sameSign(dotProd, manifold.distance)) {
                 if (otherBody instanceof TileBody) {
                     // confirm that body came from past this thing
-                    float resolutionPosition = body.aabb.xy.plus(cumulativeResolution).plus(manifold.result).dot(manifold.axis);
-                    float lastPosition = body.lastPosition.dot(manifold.axis);
 
-                    if (CollisionUtilities.canTileCollisionCanBeSkipped((TileBody) otherBody, manifold, resolutionPosition, lastPosition)) {
+                    // use the relative position between the centers of the bodies
```
Comment (MondayHopscotch) [inline jump-core/src/main/java/com/bitdecay/jump/collision/CollisionUtilities.java]: Might be a meaningless change. This way makes more sense to me, but it also has more math (therefore slower). Might make sense to just change it back if it wasn't broken.

File: jump-core/src/main/java/com/bitdecay/jump/collision/CollisionUtilities.java [hunk 2]
```diff
@@ -11,24 +11,26 @@
...
-//            // The actor was already inside the tileBody before it moved, so we can skip it.
-//            return true;
-//        }
+        // XXX: This + 0.0001f is to account for minute floating point rounding issues that cause the raw math to be off
+        // by tiny fractions. We want to basically account for these fractions and correctly enforce this case.
+        // See that this fails: assertEquals(0.593822f, 32.593822f - 32.0f, 0);
+        if (lastPosition + 0.001f < resolutionPosition) {
+            // The actor was already inside the tileBody before it moved, so we can skip it.
+            return true;
+        }
```
Comment (MondayHopscotch) [inline jump-core/src/main/java/com/bitdecay/jump/collision/CollisionUtilities.java]: This is the real fix in this PR
