### PR TITLE
Fix one-ways. Split rendering and collision neighbor values. UI cleanup

### LINKED ISSUE #58: Fix nValue for one-way platforms
They don't update properly and they should. One piece of consideration is we need two nValues. One for collisions and one for rendering.

### PR DESCRIPTION
**Pull request by MondayHopscotch**
Fixes #58

This fixed a bug hiding in one way platforms that caused them to only work in positive y coordinates. That's fixed now.

UI is cleaned up just a little bit.

There are now 2 neighbor values: one for rendering and one for collisions.

### CODE REVIEW

File: jump-core/src/main/java/com/bitdecay/jump/collision/SATResolution.java [hunk 1]
```diff
@@ -72,7 +72,7 @@ public void compute(BitBody body, BitBody otherBody, BitRectangle resolvedPositi
                                 float resolutionPosition = body.aabb.xy.plus(axisOver.axis.times(axisOver.distance)).dot(axisOver.axis);
                                 float lastPosition = body.lastPosition.dot(axisOver.axis);
 
-                                if (!MathUtils.sameSign(resolutionPosition, lastPosition) || Math.abs(lastPosition) < Math.abs(resolutionPosition)) {
+                                if (!MathUtils.sameSign(resolutionPosition, lastPosition) || (lastPosition < resolutionPosition)) {
```
Comment (MondayHopscotch) [inline jump-core/src/main/java/com/bitdecay/jump/collision/SATResolution.java]: I over-complicated this by doing the math.abs() call. Since we get these values from dot products, they are already in the exact units we need for a direct comparison.
